//! Capture a build identity so a tester's bug report / session trace can name
//! the exact commit. `git describe --always --dirty` yields the short commit
//! (plus `-dirty` for uncommitted changes); on a shallow CI clone it still
//! returns the SHA, and with no `.git` (a source tarball, `cargo install` from
//! crates.io) the command fails and the code falls back to `CARGO_PKG_VERSION`.
//! Runs for all feature combos (build scripts can't be feature-gated cleanly);
//! the cost is one git invocation, and only AI code reads `LEGION_AI_BUILD`.
use std::process::Command;

/// Walk `wiki/` and generate `$OUT_DIR/wiki_embedded.rs`: a sorted static table
/// of `(relative_path, include_str!(page))` entries. The table is `include!`d by
/// `ai/tools/wiki.rs` (so it only reaches non-`ai` builds as an unused file in
/// OUT_DIR), making the Legion knowledge wiki part of every AI build — including
/// prebuilt release binaries — with no corpus files to locate at run time.
fn embed_wiki() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default();
    let root = std::path::Path::new(&manifest).join("wiki");
    let mut pages: Vec<String> = Vec::new();
    fn walk(dir: &std::path::Path, root: &std::path::Path, out: &mut Vec<String>) {
        let Ok(rd) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in rd.flatten() {
            let p = entry.path();
            if p.is_dir() {
                walk(&p, root, out);
            } else if p.extension().and_then(|e| e.to_str()) == Some("md") {
                if let Ok(rel) = p.strip_prefix(root) {
                    out.push(rel.to_string_lossy().replace('\\', "/"));
                }
            }
        }
    }
    walk(&root, &root, &mut pages);
    pages.sort(); // deterministic table order across platforms

    let mut src = String::from(
        "/// Generated by build.rs from `wiki/` — do not edit.\n\
         pub(crate) static WIKI_EMBEDDED: &[(&str, &str)] = &[\n",
    );
    for rel in &pages {
        // Re-run when any page changes (a dir-level rerun-if-changed only sees
        // adds/removes, not edits).
        println!("cargo:rerun-if-changed=wiki/{rel}");
        src.push_str(&format!(
            "    ({rel:?}, include_str!({:?})),\n",
            root.join(rel).to_string_lossy()
        ));
    }
    src.push_str("];\n");
    println!("cargo:rerun-if-changed=wiki");
    let out = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("wiki_embedded.rs");
    std::fs::write(out, src).expect("write wiki_embedded.rs");
}

fn main() {
    embed_wiki();
    let build = Command::new("git")
        .args(["describe", "--always", "--dirty", "--tags"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_owned())
        .filter(|s| !s.is_empty());
    if let Some(b) = build {
        println!("cargo:rustc-env=LEGION_AI_BUILD={b}");
    }
    // Re-run when HEAD actually moves. `.git/logs/HEAD` (the reflog) is appended
    // on every commit / checkout / reset / merge / pull — including a same-branch
    // commit, which leaves `.git/HEAD` (a symref) byte-identical and would NOT
    // retrigger. Emitting any rerun-if-changed disables Cargo's package-file
    // fallback, so we must name the file that genuinely changes.
    for f in [".git/logs/HEAD", ".git/HEAD"] {
        if std::path::Path::new(f).exists() {
            println!("cargo:rerun-if-changed={f}");
        }
    }
}
